/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_formularios;

/**
 *
 * @author DIA
 */
public class formEjemplo1 extends javax.swing.JFrame {

    /**
     * Creates new form formEjemplo1
     */
    public formEjemplo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        btnFor = new javax.swing.JButton();
        btnWhile = new javax.swing.JButton();
        btnDowhile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        btnMCD = new javax.swing.JButton();
        btnVector = new javax.swing.JButton();
        btnMatriz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumero.setText("Número 1:");

        btnFor.setText("for");
        btnFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForActionPerformed(evt);
            }
        });

        btnWhile.setText("while");
        btnWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhileActionPerformed(evt);
            }
        });

        btnDowhile.setText("do while");
        btnDowhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDowhileActionPerformed(evt);
            }
        });

        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        jScrollPane1.setViewportView(txtRespuesta);

        jLabel1.setText("Número 2:");

        btnMCD.setText("MCD");
        btnMCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMCDActionPerformed(evt);
            }
        });

        btnVector.setText("Vector");
        btnVector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVectorActionPerformed(evt);
            }
        });

        btnMatriz.setText("Matriz");
        btnMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnFor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMCD))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnWhile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDowhile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMatriz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFor)
                    .addComponent(btnMCD)
                    .addComponent(btnVector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWhile)
                    .addComponent(btnMatriz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDowhile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForActionPerformed
        // TODO add your handling code here:
        //Variables
        int num, i,producto;
        
        num=Integer.parseInt(txtNumero1.getText());
        //Lógica
        txtRespuesta.setText("Tabla de multiplicar con bucle - for\n");
        for (i=1;i<=12;i++) {
            producto=num*i;
            //Escribimos en txtRespuesta
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
        }
    }//GEN-LAST:event_btnForActionPerformed

    private void btnWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhileActionPerformed
        // TODO add your handling code here:
        //Variables
        int num, i=1,producto;
        
        num=Integer.parseInt(txtNumero1.getText());
        //Lógica
        txtRespuesta.setText("Tabla de multiplicar con bucle - while\n");
        while (i<=12) {
            producto=num*i;
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
            i++; //i=i+1
        }
    }//GEN-LAST:event_btnWhileActionPerformed

    private void btnDowhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDowhileActionPerformed
        // TODO add your handling code here:
        //Variables
        int num, i=1,producto;
        
        num=Integer.parseInt(txtNumero1.getText());
        //Lógica
        txtRespuesta.setText("Tabla de multiplicar con bucle - do while\n");
        do {
            producto=num*i;
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
            i=i+1;
        }while (i<=12);
    }//GEN-LAST:event_btnDowhileActionPerformed

    private void btnMCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMCDActionPerformed
        // TODO add your handling code here:
        //Variables
        int num1, num2,residuo=-1, aux;
        int aux_num1, aux_num2;
        
        //Lectura de datos
        num1=Integer.parseInt(txtNumero1.getText());
        num2=Integer.parseInt(txtNumero2.getText());
        
        //guardamos los valores para utilizarlos en la impresión final
        aux_num1=num1;
        aux_num2=num2;
        //Validar que num1 >=num2
        if (num2>num1) {
            //intercambiar con la ayuda de una variable auxiliar
            aux=num1;
            num1=num2;
            num2=aux;
        }
        //implementar la lógica para encontrar el MCD
        txtRespuesta.setText("Calculamos el MCD de los números "+num1+" y "+num2+" paso a paso\n");
        while(residuo!=0) {
            txtRespuesta.append("MCD("+num1+","+num2+") = ");
            residuo=num1%num2;
            num1=num2;
            num2=residuo;
            txtRespuesta.append("MCD("+num1+","+num2+")\n");
        }
        txtRespuesta.append("El MCD de "+aux_num1+" y "+aux_num2+" es: "+num1+"\n");
    }//GEN-LAST:event_btnMCDActionPerformed

    private void btnVectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVectorActionPerformed
        // TODO add your handling code here:
        int[] notas= {15,18,20,16,7,4,12,15,14};  
        int i=0, max=notas.length;
        txtRespuesta.setText("Los elementos del arreglo son: \n");
        
        while (i<max){
            txtRespuesta.append(""+notas[i]+"\n");
            i++;
        }

    }//GEN-LAST:event_btnVectorActionPerformed

    private void btnMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizActionPerformed
        // TODO add your handling code here:
        int[][] notas={{2,3,4,5,6,1,34,55,3,232,454},{9,10,11}};
        int i=0, j=0;
        txtRespuesta.setText("Los elementos de la matriz son: \n");
        for (i=0;i<notas.length;i++) { //recorre las filas
            for (j=0;j<notas[i].length;j++) {
                txtRespuesta.append(notas[i][j]+" ");
            }
            txtRespuesta.append("\n");
        }
    }//GEN-LAST:event_btnMatrizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEjemplo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDowhile;
    private javax.swing.JButton btnFor;
    private javax.swing.JButton btnMCD;
    private javax.swing.JButton btnMatriz;
    private javax.swing.JButton btnVector;
    private javax.swing.JButton btnWhile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
