/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack_formularios;

import static java.lang.Math.pow;

/**
 *
 * @author DIA
 */
public class formEjemplo1 extends javax.swing.JFrame {

    /**
     * Creates new form formEjemplo1
     */
    public formEjemplo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        btnFor = new javax.swing.JButton();
        btnWhile = new javax.swing.JButton();
        btnDowhile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        btnCubo = new javax.swing.JButton();
        btnFactorial = new javax.swing.JButton();
        btnSumatoria = new javax.swing.JButton();
        btnSumaRango = new javax.swing.JButton();
        txtNumero2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tabla de multiplicar");

        lblNumero.setText("Número");

        btnFor.setText("For");
        btnFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnForActionPerformed(evt);
            }
        });

        btnWhile.setText("While");
        btnWhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhileActionPerformed(evt);
            }
        });

        btnDowhile.setText("Do while");
        btnDowhile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDowhileActionPerformed(evt);
            }
        });

        txtRespuesta.setColumns(20);
        txtRespuesta.setRows(5);
        jScrollPane1.setViewportView(txtRespuesta);

        btnCubo.setText("al cubo");
        btnCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuboActionPerformed(evt);
            }
        });

        btnFactorial.setText("Factorial");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        btnSumatoria.setText("Sumatoria");
        btnSumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumatoriaActionPerformed(evt);
            }
        });

        btnSumaRango.setText("Sumar Rango");
        btnSumaRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaRangoActionPerformed(evt);
            }
        });

        jLabel1.setText("Número 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnDowhile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(btnFor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnWhile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSumatoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFactorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(25, 25, 25))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSumaRango))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFor)
                    .addComponent(btnCubo)
                    .addComponent(btnSumaRango))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWhile)
                    .addComponent(btnSumatoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDowhile)
                    .addComponent(btnFactorial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForActionPerformed
        //Variables
        int num, i, producto;
        
        //Leo el contenido de txtNumero, lo parseo y lo guardo en la variable num
        num=Integer.parseInt(txtNumero1.getText());
        
        //Lógica
        txtRespuesta.setText("");
        txtRespuesta.setText("Tabla de multiplicar con bucle -for\n");
        for(i=1; i<=12; i++) {
            producto=num*i;
            //Impresión en txtRespuesta
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
        }
        
    }//GEN-LAST:event_btnForActionPerformed

    private void btnWhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhileActionPerformed
        int num, i, producto;
        
        num=Integer.parseInt(txtNumero1.getText());
        
        //Logica
        txtRespuesta.setText("Tabla de multiplicar con bucle - while\n");
        i=1;
        while (i<=12) {
            producto=num*i;
            txtRespuesta.append(num+" x  "+i+" = "+producto+"\n");
            i++;
        }
    }//GEN-LAST:event_btnWhileActionPerformed

    private void btnDowhileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDowhileActionPerformed
        // TODO add your handling code here:
        int num, i, producto;
        
        num=Integer.parseInt(txtNumero1.getText());
        
        //Logica
        txtRespuesta.setText("Tabla de multiplicar con bucle - do while\n");
        i=1;
        do {
            producto=num*i;
            txtRespuesta.append(num+" x "+i+" = "+producto+"\n");
            i++;
        }while (i<=12);
    }//GEN-LAST:event_btnDowhileActionPerformed

    private void btnCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuboActionPerformed
        // TODO add your handling code here:
        int i, num, cubo;
        num=Integer.parseInt(txtNumero1.getText());
        
        //Logica
        txtRespuesta.setText("Impresión de número al cubo desde 1 hasta "+num+"\n");
        
        for(i=1;i<=num;i++) {
            cubo=(int) pow(i,3);
            txtRespuesta.append("El número "+i+" al cubo es: "+cubo+"\n");
        }
    }//GEN-LAST:event_btnCuboActionPerformed

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
        // TODO add your handling code here:
        int factorial, i, num;
        num=Integer.parseInt(txtNumero1.getText());
        
        txtRespuesta.setText("Impresión del factorial del número "+num+"\n");
        /*
        0! = 1
        1! = 1
        2! = 1! x 2 = 2
        3! = 2! x 3 = 6
        4! = 3! x 4 = 24
        num!= factorial x num
        */
        i=1;
        factorial=1;
        while (i<=num) {
            factorial=i*factorial;
            txtRespuesta.append(i+"! ="+factorial+"\n");
            i++;
        }
        
    }//GEN-LAST:event_btnFactorialActionPerformed

    private void btnSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumatoriaActionPerformed
        // TODO add your handling code here:
        int sumatoria=0, i, num;
        num=Integer.parseInt(txtNumero1.getText());
        
        txtRespuesta.setText("Impresión de la sumatoria desde 1 hasta "+num+"\n");
        i=1;
        while (i<=num){
            sumatoria=sumatoria +i;
            txtRespuesta.append("agregamos "+i+" a la sumatoria y el resultado es: "+sumatoria+"\n");
            i++;
        }
        
        
    }//GEN-LAST:event_btnSumatoriaActionPerformed

    private void btnSumaRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaRangoActionPerformed
        // TODO add your handling code here:
        int num1,num2,i;
        int suma=0;
        
        num1=Integer.parseInt(txtNumero1.getText());
        num2=Integer.parseInt(txtNumero2.getText());
        
        //num2 debe ser mayor que num1
        if (num2>=num1) {
            txtRespuesta.setText("Impresión de la sumatoria desde "+num1+" hasta "+num2+"\n");
            i=num1;
//            while (i<=num2) {
//                txtRespuesta.append(""+i+"\n");
//                suma=suma+i;
//                i++;
//            }
            do {
                txtRespuesta.append(""+i+"\n");
                suma=suma+i;
                i++;
            }while(i<=num2);
            
            txtRespuesta.append("La suma de los números dentro del rango es: "+suma);
        } else {
            txtRespuesta.setText("Número 1 debe ser menor que número 2\n");
        }
    }//GEN-LAST:event_btnSumaRangoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEjemplo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEjemplo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCubo;
    private javax.swing.JButton btnDowhile;
    private javax.swing.JButton btnFactorial;
    private javax.swing.JButton btnFor;
    private javax.swing.JButton btnSumaRango;
    private javax.swing.JButton btnSumatoria;
    private javax.swing.JButton btnWhile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
