/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIA
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnOrdenar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnBuscarNumero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumero.setText("Número");

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnBuscarNumero.setText("Buscar");
        btnBuscarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrdenar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumero)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarNumero)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarNumero))
                .addGap(27, 27, 27)
                .addComponent(btnOrdenar)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        int [] numero = {6,5,2,1,8,10,20,4,6,2,6,5,5,6};
        int i,j,aux;
        txtResultado.setText("El arreglo original es: \n");
        txtResultado.append("{");
        for(i=0; i<numero.length;i++) {
            txtResultado.append(numero[i]+ " ");
        }
        txtResultado.append("}\n\n");
        for (i=0; i<numero.length;i++){ //con este bucle yo voy a hacer las comparaciones
            for (j=i+1; j<numero.length;j++) {
                if (numero[i]>numero[j]){ //Preguntamos si numero[i]>numero[j], si es así intercambiamos
                    //Intercambiamos
                    //guardo el valor original de numero[i] en aux
                    aux=numero[i];
                    //Reemplazo el valor orignal de numero[i] con numero[j]
                    numero[i]=numero[j];
                    //numero[j] le asigno el valor original de numero[i] que se encuentra en aux
                    numero[j]=aux;
                }
            }
        }
        //Imprimimos el arreglo 
        txtResultado.append("El arreglo ordenado es: \n");
        txtResultado.append("{");
        for(i=0; i<numero.length;i++) {
            txtResultado.append(numero[i]+ " ");
        }
        txtResultado.append("}");
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnBuscarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNumeroActionPerformed
        // TODO add your handling code here:
        int[] numero={1,2,3,4,6,7,8,9,13,15,16,20,21,60,70};
        int i,mitad, limiteInferior=0, limiteSuperior=numero.length-1;
        int numeroBuscar;
        boolean encontrado=false;
        
        //Imprimimos el arreglo 
        txtResultado.append("El arreglo ordenado es: \n");
        txtResultado.append("{");
        for(i=0; i<numero.length;i++) {
            txtResultado.append(numero[i]+ " ");
        }
        txtResultado.append("}\n\n");
        
        numeroBuscar=Integer.parseInt(txtNumero.getText());
        //Buscar mientras el límite inferior sea menor o igual que el límite superior y que no haya sido encontrado
        while (limiteInferior<=limiteSuperior && !encontrado) {
            //Defino la mitad del arreglo
            mitad=(limiteInferior+limiteSuperior)/2;
            if (numero[mitad]==numeroBuscar) {
                encontrado=true;
            } else if(numero[mitad]>numeroBuscar) {
                limiteSuperior= mitad-1; //Busca en la primera mitad
            } else {
                limiteInferior=mitad+1; //Busca en la segunda mitad                
            }
        }
        if (encontrado) {
            txtResultado.append("El número está en el arreglo");
        } else {
            txtResultado.append("El número no está en el arreglo");
        }
    }//GEN-LAST:event_btnBuscarNumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarNumero;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
