/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DIA
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        btnMostrarArreglo = new javax.swing.JButton();
        btnMostrarMatriz = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnBuscarNumero = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        txtAgregarNumero = new javax.swing.JTextField();
        btnAgregarNum = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        btnMostrarArreglo.setText("mostrarArreglo");
        btnMostrarArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarArregloActionPerformed(evt);
            }
        });

        btnMostrarMatriz.setText("mostrar Matriz");
        btnMostrarMatriz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarMatrizActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnBuscarNumero.setText("Buscar número");
        btnBuscarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNumeroActionPerformed(evt);
            }
        });

        btnAgregarNum.setText("Agregar número");
        btnAgregarNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrarMatriz)
                            .addComponent(btnMostrarArreglo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(txtAgregarNumero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarNumero)
                            .addComponent(btnAgregarNum)
                            .addComponent(btnOrdenar))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarArreglo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAgregarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregarNum)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarMatriz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarNumero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarArregloActionPerformed
        // TODO add your handling code here:
        int[] numeros=new int[4];
        numeros[0]=-1;
        numeros[1]=-2;
        numeros[2]=-3;

        
        int masNumeros[]={4,1,2,20,100,39,48};
        String diasSemana[]={"Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo"};
        
        int cantNumeros, cantMasNumeros;
        
        //Cantidad de elementos de los arreglos
        cantNumeros=numeros.length;
        cantMasNumeros=masNumeros.length;
        txtResultado.setText("tamaño de arreglo numeros: "+cantNumeros+"\ntamaño de arreglo cantMasNumeros: "+cantMasNumeros+"\n");
        
        //Imprimimos el contenido de los arreglos
        txtResultado.append("Imprimimos el contenido de los arreglos:\n");
        for (int i=0; i<=numeros.length-1;i++) {
            txtResultado.append(numeros[i]+" ");
        }
        txtResultado.append("\n");
        for (int num:masNumeros)
            txtResultado.append(num+" ");
        txtResultado.append("\n");
        txtResultado.setText("");
        for (String dia:diasSemana)
            txtResultado.append(dia+"\n");        
    }//GEN-LAST:event_btnMostrarArregloActionPerformed

    private void btnMostrarMatrizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarMatrizActionPerformed
        // TODO add your handling code here:
        //Un arreglo de enteros de 2x3
        int[][] notas=new int[2][3];
        notas[0][0]=20;
        notas[0][1]=18;
        notas[0][2]=11;
        notas[1][0]=15;
        notas[1][1]=13;
        notas[1][2]=10;
        
        int[][] notas2= {   {1,3,5}, //fila 0 (las filas se recorren con i)
                            {5,4,1,16}, //fila 1
                            {7,9,61,13,56} //fila 2
                        };
        
        //imprimimos la matriz de notas
        int i,j;
        for (i=0;i<=notas2.length-1;i++) {
            for(j=0;j<=notas2[i].length-1;j++) {
                txtResultado.append(notas2[i][j]+" ");
            }
            txtResultado.append("\n");
        }
        
    }//GEN-LAST:event_btnMostrarMatrizActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        int[] numeros={6,5,3,45,123,56,-1,2,2,1,1,2};
        int i,j;
        int auxiliar;
        //Ordenamos
        txtResultado.setText("Arreglo original:\n");
        for (int num:nuevosNumeros)
            txtResultado.append(num+" ");
        
        for (i=0; i<=nuevosNumeros.length-1; i++) {
            for (j=i+1;j<=nuevosNumeros.length-1;j++) {
                if (nuevosNumeros[i]>nuevosNumeros[j]) { //Comparo los números
                    //intercambiamos
                    auxiliar=nuevosNumeros[i]; //Guardamos en auxiliar el valor original de numeros[i]
                    nuevosNumeros[i]=nuevosNumeros[j]; //Reemplazamos numeros[i] con el valor de numeros[j]
                    nuevosNumeros[j]=auxiliar; //Reemplazamos numeros[j] con el valor original de numeros[i] (auxiliar)
                }
            }
        }
        //Imprimirmos el arreglo ordenado
        txtResultado.append("\nArreglo ordenado:\n");
        for (int num:nuevosNumeros)
            txtResultado.append(num+" ");
        
        
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnBuscarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNumeroActionPerformed
        // TODO add your handling code here:
        //int[] numeros={1,2,3,4,5,6,7,8,9,10,15,17,24,45,100,121};
        int mitad,limInferior, limSuperior, numeroBuscar;
        boolean encontrado;
        limInferior=0;
        limSuperior=nuevosNumeros.length-1;
        numeroBuscar=Integer.parseInt(txtNumero.getText());
        encontrado=false;
        
        txtResultado.setText("El arreglo ordenado es:\n");
        for (int numero:nuevosNumeros)
            txtResultado.append(numero+" ");
        txtResultado.append("\n");
        
        //Buscar
        while ((limInferior<=limSuperior) && !encontrado) { //Mientras limInferior sea menor o igual que limSuperior y no haya encontrado el número
            mitad=(limInferior+limSuperior)/2;
            
            if(nuevosNumeros[mitad]==numeroBuscar) {
                encontrado=true;
            } else if (nuevosNumeros[mitad]>numeroBuscar){
                //Estoy en la primera mitad, actualizo el límite superior
                limSuperior=mitad-1;
            } else {
                //Estoy en la segunda mitad, actualizo el límite inferior
                limInferior=mitad+1;
            }
        }
        if (encontrado) {
            txtResultado.append("\nSe ha encontrado el número");
        } else {
            txtResultado.append("\nNo se ha encontrado el número");
        }
        
    }//GEN-LAST:event_btnBuscarNumeroActionPerformed
    int[] nuevosNumeros=new int[5];
    int i=0;
    private void btnAgregarNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNumActionPerformed
        // TODO add your handling code here:
        int num=Integer.parseInt(txtAgregarNumero.getText());
        nuevosNumeros[i]=num;
        i++;
        txtResultado.append(i+". el numero agregado es: "+num+"\n");
    }//GEN-LAST:event_btnAgregarNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarNum;
    private javax.swing.JButton btnBuscarNumero;
    private javax.swing.JButton btnMostrarArreglo;
    private javax.swing.JButton btnMostrarMatriz;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAgregarNumero;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
